### ISSUE TITLE
Show progress indicator during linting

### ISSUE THREAD

**Issue by sebschn01** [SAP/ui5-linter#194]
When running the linter on a large project, the user has no feedback for progress during execution of linter.
I personally was not sure if the linter was actually running, or if it was stuck. 

I was running a linter on a large folder structure, and linting took ~1.5 minutes (10k+ files)
Having no progress indication also is visible for smaller projects/ folders. 
To easily get a sample project where linting also takes several seconds i used https://github.com/SAP/generator-easy-ui5 to get a fresh project. 
Running ui5lint in this sample project also takes ~5seconds and no progress indication is visible.

It would be great to have some sort of visible progress indicator to know that linting is in progress.

Some options i can think of are: 
- using "blinking" dots  . . .
- using a "rotating line"  -  \  |  /  -  \  |  /  -
- some text feedback that "linting in progress"

![image](https://github.com/SAP/ui5-linter/assets/163006461/52fe34b6-a620-4e19-a24a-2674bee007c6)

**Comment by matz3** [comment]
Thank you for bringing this up 👍🏻

I understand the general idea of this feature, but I don't think it is valuable to implement and for most cases not even necessary.

Let me explain why:
- ESLint does also not print any progress indication and we strive to make UI5 linter an ESLint plugin (see https://github.com/SAP/ui5-linter/issues/45 on why this is not a straight-forward step). With such an integration the feature would be gone.
- If you're about to cancel a run because you think the tool takes way longer than expected, you can add the `--verbose` flag to get output from the tool which should help to see what's happening. A progress indicator would not provide any actual value as (depending on how it is implemented) it might still spin or do something, but it's still unknown whether it is stuck or not, and at which step/file.

So, I think we should rather focus our limited capacity into improving the rules (the main benefit of this tool) and an integration into ESLint.
