### ISSUE TITLE
fe lrop v4 displays linter ignore pattern when loading object page in UI5 nightly and untested (1.132.0)

### ISSUE THREAD

**Issue by heimwege** [SAP/ui5-linter#412]
Hey guys,

I just noticed that our fe v4 lrop displays `/* ui5lint-disable */` when loading an object page (see screenshot). Maybe this is not even the fault of the ui5linter. I don't know. Let's start the investigation here 🕵🏻 

## Expected Behavior

This text should not be displayes

## Current Behavior

see text in screenshot

![image](https://github.com/user-attachments/assets/30f75c83-36e3-4152-8adc-f28f14c82aea)

## Steps to Reproduce the Issue

I guess just load a lrop with the respective version 🤷🏻 

## Context

- UI5 linter version: none
- Node.js version: 18 something (wasn't my pc)
- npm version: 🤷🏻  (wasn't my pc)
- OS/Platform: windows
- Browser *(if relevant)*: chrome
- Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

not needed

**Comment by codeworrior** [comment]
The placeholders in sap.fe use *.fragment.html as extension of their HTML files. This is a suggestion of the UI5 runtime to easily allow to bundle them and still express their mime type (somewhat).

As the linter complains about HTML and JSON views/fragments, those files are reported as issues and sap.fe colleagues tried to fix this with linter directives in the files. 

Technically, the files are no UI5 fragments, however. I'll therefore suggest to the colleagues to rather exclude those files form listing. There's no point in linting them.

As this is not a UI5 linter issue, I'll close the issue here.

**Comment by heimwege** [comment]
@codeworrior so I should rather route this to the fe colleagues?

**Comment by codeworrior** [comment]
No, not necessary, they've fixed it already earlier today in 1.131 and master codelines. I'll add you on CC on the corresponding changes.
